import type {
  CanvasPreset,
  DuoBeat,
  GameModeId,
  GameModeMetadata,
  MemoryTwist,
  PromptCard,
  RemixRule,
  StoryBeat,
} from "./types";

export const CANVAS_PRESETS: readonly CanvasPreset[] = [
  {
    id: "square",
    label: "Cozy square",
    width: 960,
    height: 960,
    description: "The all-rounder for characters, doodles, and chaos.",
  },
  {
    id: "landscape",
    label: "Story wide",
    width: 1280,
    height: 800,
    description: "Extra room for scenes, panels, and dramatic entrances.",
  },
  {
    id: "portrait",
    label: "Tall tale",
    width: 800,
    height: 1120,
    description: "Great for posters, creatures, and accidental comics.",
  },
] as const;

export const GAME_MODES: readonly GameModeMetadata[] = [
  {
    id: "classic-chain",
    name: "Classic Chain",
    eyebrow: "Prompt · draw · guess",
    icon: "✦",
    description:
      "Plant an idea, pass it across the table, and watch it wobble into something new.",
    howItFeels: "A warm-up that steadily turns into a private inside joke.",
    rhythm: "Write → draw → guess → begin a fresh chain",
    accent: "#e66d50",
    accentSoft: "#ffe1d8",
    recommendedRounds: 9,
    defaultTimerSeconds: 60,
    supportsRandomPrompts: true,
    highlights: ["Balanced turns", "Fresh prompt every 3 rounds", "Great first game"],
  },
  {
    id: "memory-drift",
    name: "Memory Drift",
    eyebrow: "Look · hide · redraw",
    icon: "◌",
    description:
      "Flash the last drawing for a few seconds, hide it, then rebuild the memory you think you saw.",
    howItFeels: "A visual whisper that becomes gloriously unreliable.",
    rhythm: "Make an original → flash → redraw → repeat",
    accent: "#7357c7",
    accentSoft: "#e9e1ff",
    recommendedRounds: 7,
    defaultTimerSeconds: 55,
    supportsRandomPrompts: true,
    highlights: ["Shrinking preview", "Escalating twists", "Big reveal payoff"],
  },
  {
    id: "blind-prompt",
    name: "Blind Prompt",
    eyebrow: "Clues arrive slowly",
    icon: "?",
    description:
      "Draw a hidden idea from four increasingly useful clues without ever seeing the full sentence.",
    howItFeels: "A tiny cooperative mystery with one very confused illustrator.",
    rhythm: "Broad clue → mood → place → ingredients",
    accent: "#187e76",
    accentSoft: "#d8f3ed",
    recommendedRounds: 6,
    defaultTimerSeconds: 70,
    supportsRandomPrompts: true,
    highlights: ["Timed clue ladder", "Secret target", "Perfect for bluffing"],
  },
  {
    id: "remix-mode",
    name: "Remix Mode",
    eyebrow: "Keep it · change it",
    icon: "↻",
    description:
      "Inherit the last picture and obey a new art-direction card every round.",
    howItFeels: "Collaborative doodling with a mischievous creative director.",
    rhythm: "Original → remix → wilder remix → finale",
    accent: "#cf4f86",
    accentSoft: "#ffe0ee",
    recommendedRounds: 8,
    defaultTimerSeconds: 65,
    supportsRandomPrompts: true,
    highlights: ["20 remix rules", "Chaos ramps gently", "One shared canvas lineage"],
  },
  {
    id: "speed-chaos",
    name: "Speed Chaos",
    eyebrow: "No time for perfection",
    icon: "⚡",
    description:
      "Tiny timers, punchy prompts, and guesses made before either of you can overthink.",
    howItFeels: "Fast, forgiving, and reliably ridiculous.",
    rhythm: "Sprint draw → snap guess → sprint draw",
    accent: "#db8c15",
    accentSoft: "#fff0c7",
    recommendedRounds: 10,
    defaultTimerSeconds: 18,
    supportsRandomPrompts: true,
    highlights: ["10–25 second turns", "Rapid alternation", "Low-stakes marks"],
  },
  {
    id: "story-canvas",
    name: "Story Canvas",
    eyebrow: "A comic for two",
    icon: "▤",
    description:
      "Build a visual story panel by panel, alternating drawings with captions and plot turns.",
    howItFeels: "Like inventing a bedtime story with someone who keeps adding raccoons.",
    rhythm: "Draw a panel → caption it → continue the panel",
    accent: "#3470b8",
    accentSoft: "#dcecff",
    recommendedRounds: 8,
    defaultTimerSeconds: 75,
    supportsRandomPrompts: true,
    highlights: ["Story beat cards", "Alternating skills", "Comic-strip gallery"],
  },
  {
    id: "guess-evolution",
    name: "Guess Evolution",
    eyebrow: "One idea, many mutations",
    icon: "∞",
    description:
      "Start once, then alternate drawing and guessing using only the most recent interpretation.",
    howItFeels: "The purest telephone effect, stretched into a long-running duet.",
    rhythm: "Seed prompt → draw → guess → draw the guess",
    accent: "#678431",
    accentSoft: "#e9f3d1",
    recommendedRounds: 9,
    defaultTimerSeconds: 55,
    supportsRandomPrompts: true,
    highlights: ["No resets", "Strict information handoff", "Best before-and-after reveal"],
  },
] as const;

export const GAME_MODE_BY_ID = Object.fromEntries(
  GAME_MODES.map((mode) => [mode.id, mode]),
) as Record<GameModeId, GameModeMetadata>;

export const PROMPT_CARDS: readonly PromptCard[] = [
  {
    id: "moon-noodles",
    text: "A moon chef serving noodles to a tiny dragon",
    category: "unlikely job",
    mood: "gentle and proud",
    setting: "a very small night-time restaurant",
    ingredients: ["something celestial", "a hungry mythical guest"],
  },
  {
    id: "bus-stop-whale",
    text: "A whale waiting politely at a rainy bus stop",
    category: "animal out of place",
    mood: "patient but slightly awkward",
    setting: "somewhere commuters gather in bad weather",
    ingredients: ["a huge sea creature", "public transport etiquette"],
  },
  {
    id: "detective-sandwich",
    text: "A detective sandwich investigating its missing pickle",
    category: "food with a mission",
    mood: "dead serious about something silly",
    setting: "a suspicious lunch scene",
    ingredients: ["a snack in a tiny coat", "one vanished crunchy clue"],
  },
  {
    id: "ghost-gardener",
    text: "A shy ghost growing sunflowers in a haunted attic",
    category: "secret hobby",
    mood: "spooky, soft, and hopeful",
    setting: "the highest room in an old house",
    ingredients: ["a transparent gardener", "flowers that love daylight"],
  },
  {
    id: "sock-concert",
    text: "Three lost socks performing a stadium rock concert",
    category: "tiny spectacle",
    mood: "far too dramatic",
    setting: "a huge stage with bright lights",
    ingredients: ["laundry without partners", "an adoring crowd"],
  },
  {
    id: "capybara-spa",
    text: "A capybara running a cloud spa for stressed birds",
    category: "animal business",
    mood: "deeply relaxed",
    setting: "somewhere soft above the ground",
    ingredients: ["a calm round host", "winged customers"],
  },
  {
    id: "robot-picnic",
    text: "Two robots on a picnic trying to understand ants",
    category: "curious friendship",
    mood: "scientific and sweet",
    setting: "a checkered blanket outdoors",
    ingredients: ["metal friends", "a very organized insect line"],
  },
  {
    id: "wizard-laundry",
    text: "A wizard whose laundry spell has become too powerful",
    category: "magic mishap",
    mood: "panicked but colorful",
    setting: "a room filling with enchanted clothes",
    ingredients: ["a wand", "rebellious clean fabric"],
  },
  {
    id: "pigeon-mayor",
    text: "A pigeon mayor opening a suspicious new fountain",
    category: "important ceremony",
    mood: "official with a hint of trouble",
    setting: "a crowded town square",
    ingredients: ["a feathered leader", "something newly full of water"],
  },
  {
    id: "snail-racer",
    text: "A snail crossing the finish line in a rocket-powered teacup",
    category: "impossible sport",
    mood: "triumphant and bewildering",
    setting: "the end of a high-speed race",
    ingredients: ["a famously slow athlete", "very fast crockery"],
  },
  {
    id: "monster-bakery",
    text: "A many-eyed monster decorating one perfect cupcake",
    category: "delicate task",
    mood: "focused and unexpectedly adorable",
    setting: "a flour-dusted kitchen",
    ingredients: ["too many eyes", "one tiny frosted dessert"],
  },
  {
    id: "cat-museum",
    text: "A cat museum where every painting is secretly a door",
    category: "mysterious place",
    mood: "elegant and curious",
    setting: "quiet galleries after closing time",
    ingredients: ["a whiskered visitor", "art that leads elsewhere"],
  },
  {
    id: "frog-orchestra",
    text: "A frog conducting an orchestra during a thunderstorm",
    category: "weather performance",
    mood: "grand and splashy",
    setting: "an outdoor stage in heavy rain",
    ingredients: ["an amphibian maestro", "musical lightning"],
  },
  {
    id: "sleepy-volcano",
    text: "A sleepy volcano wearing pajamas and refusing to erupt",
    category: "nature with feelings",
    mood: "cozy and stubborn",
    setting: "a mountain at bedtime",
    ingredients: ["something usually explosive", "nightwear"],
  },
  {
    id: "alien-yard-sale",
    text: "An alien yard sale selling mysterious Earth souvenirs",
    category: "strange marketplace",
    mood: "friendly but questionable",
    setting: "a front lawn far from home",
    ingredients: ["an off-world shopkeeper", "ordinary objects mislabeled"],
  },
  {
    id: "penguin-postcard",
    text: "A penguin sending a tropical postcard from inside a freezer",
    category: "vacation confusion",
    mood: "cheerful and ironic",
    setting: "a very cold appliance",
    ingredients: ["a formal-looking bird", "a sunny travel message"],
  },
  {
    id: "toast-spacewalk",
    text: "A brave piece of toast taking its first spacewalk",
    category: "small heroism",
    mood: "awe-struck and crunchy",
    setting: "outside a spacecraft",
    ingredients: ["breakfast", "a safety tether among stars"],
  },
  {
    id: "raccoon-library",
    text: "A raccoon librarian guarding the forbidden snack section",
    category: "secret collection",
    mood: "hushed and suspicious",
    setting: "a library aisle no one talks about",
    ingredients: ["a masked caretaker", "books about treats"],
  },
] as const;

export const REMIX_RULES: readonly RemixRule[] = [
  { id: "dramatic", icon: "☄", title: "Maximum drama", instruction: "Make every pose and shadow feel like the final scene of a movie.", intensity: 1, tag: "mood" },
  { id: "party-hat", icon: "△", title: "Unexpected celebration", instruction: "Add evidence that a party started five seconds ago.", intensity: 1, tag: "plot" },
  { id: "tiny-friend", icon: "·", title: "Tiny companion", instruction: "Give the main subject a very small, very loyal friend.", intensity: 1, tag: "character" },
  { id: "weather", icon: "☂", title: "Weather happened", instruction: "Change the weather and show how everyone feels about it.", intensity: 1, tag: "mood" },
  { id: "suspicious", icon: "⌁", title: "Add suspicion", instruction: "Place one detail that makes the whole scene look suspicious.", intensity: 1, tag: "mystery" },
  { id: "fancy", icon: "✧", title: "Dress code: fancy", instruction: "Make at least one character outrageously overdressed.", intensity: 1, tag: "style" },
  { id: "wrong-scale", icon: "↕", title: "Wrong size", instruction: "Make one ordinary thing impossibly huge or hilariously tiny.", intensity: 2, tag: "style" },
  { id: "monster", icon: "♒", title: "Monster edition", instruction: "Turn something harmless into a monster, but keep it oddly lovable.", intensity: 2, tag: "character" },
  { id: "secret-door", icon: "▥", title: "Secret entrance", instruction: "Add a door, hatch, or portal where no entrance should be.", intensity: 2, tag: "mystery" },
  { id: "time-travel", icon: "◴", title: "Wrong century", instruction: "Move the scene into a completely different time period.", intensity: 2, tag: "plot" },
  { id: "album-cover", icon: "♪", title: "Album cover", instruction: "Remix the composition like this is a band’s unforgettable debut.", intensity: 2, tag: "style" },
  { id: "double", icon: "Ⅱ", title: "Troublesome double", instruction: "Clone one subject and make the copy behave very differently.", intensity: 2, tag: "character" },
  { id: "heist", icon: "◇", title: "It’s a heist now", instruction: "Add a target, a plan, and one comically bad disguise.", intensity: 2, tag: "plot" },
  { id: "underwater", icon: "≈", title: "Suddenly underwater", instruction: "Submerge the whole idea while preserving its most recognizable detail.", intensity: 2, tag: "style" },
  { id: "villain", icon: "♛", title: "Villain reveal", instruction: "Reveal that the least suspicious object was the mastermind all along.", intensity: 3, tag: "plot" },
  { id: "everything-food", icon: "◉", title: "Edible universe", instruction: "Turn the setting into food without changing what is happening.", intensity: 3, tag: "style" },
  { id: "gravity", icon: "↗", title: "Gravity resigned", instruction: "Make loose objects and characters float in different directions.", intensity: 3, tag: "style" },
  { id: "three-emotions", icon: "≋", title: "Emotional weather map", instruction: "Show three completely different emotions in the same scene.", intensity: 3, tag: "mood" },
  { id: "plot-twist", icon: "!", title: "Tiny plot twist", instruction: "Add one background detail that changes the meaning of everything.", intensity: 3, tag: "mystery" },
  { id: "callback", icon: "↩", title: "Bring it back", instruction: "Rescue a forgotten detail from an earlier round and make it essential.", intensity: 3, tag: "plot" },
] as const;

export const MEMORY_TWISTS: readonly MemoryTwist[] = [
  { id: "faithful-ish", icon: "○", title: "Faithful-ish", instruction: "Rebuild the big shapes first. Charming errors are welcome.", intensity: 1 },
  { id: "one-color", icon: "●", title: "One color retires", instruction: "Avoid the most obvious color you remember.", intensity: 1 },
  { id: "swap-mood", icon: "☻", title: "Mood swap", instruction: "Keep the scene, but flip its emotional tone.", intensity: 1 },
  { id: "missing-corner", icon: "⌞", title: "The missing corner", instruction: "Invent what you think was hiding in one corner.", intensity: 1 },
  { id: "mirror", icon: "↔", title: "Mirror memory", instruction: "Recreate the composition flipped left to right.", intensity: 2 },
  { id: "five-shapes", icon: "⬡", title: "Five-shape budget", instruction: "Reduce the remembered scene to five bold shapes.", intensity: 2 },
  { id: "memory-lie", icon: "~", title: "Tell one little lie", instruction: "Add one plausible detail that definitely was not there.", intensity: 2 },
  { id: "focus-shift", icon: "◎", title: "New main character", instruction: "Promote a background detail into the star.", intensity: 2 },
  { id: "symbol-only", icon: "※", title: "Symbol language", instruction: "Replace one remembered object with a symbol for it.", intensity: 3 },
  { id: "dream-logic", icon: "☾", title: "Dream logic", instruction: "Connect two remembered things in an impossible way.", intensity: 3 },
  { id: "close-up", icon: "⊙", title: "Extreme close-up", instruction: "Zoom into the detail you remember most confidently.", intensity: 3 },
  { id: "confidently-wrong", icon: "★", title: "Confidently wrong", instruction: "Commit to your foggiest memory as if it were the whole point.", intensity: 3 },
] as const;

export const STORY_BEATS: readonly StoryBeat[] = [
  { id: "establish", label: "Once upon a doodle", instruction: "Introduce a place and someone who clearly wants something." },
  { id: "arrival", label: "An arrival", instruction: "Bring in a visitor, package, noise, or omen." },
  { id: "problem", label: "Small problem, big energy", instruction: "Make an ordinary obstacle feel extremely important." },
  { id: "choice", label: "A choice", instruction: "Show a fork in the road—literal or emotional." },
  { id: "quiet", label: "Quiet beat", instruction: "Add a small sincere moment before the next surprise." },
  { id: "callback", label: "Callback", instruction: "Bring back an early object with a new purpose." },
  { id: "finale", label: "Last panel magic", instruction: "End with a payoff, a punchline, or a door left slightly open." },
] as const;

export const DUO_BEATS: readonly DuoBeat[] = [
  { id: "tiny-tribute", icon: "♡", label: "Tiny tribute", invitation: "Optional: sneak in one small thing your partner loves." },
  { id: "secret-handshake", icon: "⌁", label: "Secret handshake", invitation: "Reuse a shape or color from the opening round." },
  { id: "yes-and", icon: "+", label: "Yes, and…", invitation: "Keep one part of your partner’s idea exactly, then add your own surprise." },
  { id: "final-keepsake", icon: "✦", label: "Keepsake round", invitation: "Add one last detail only the two of you are likely to understand." },
] as const;

export const BLIND_CLUE_LADDERS = [
  { label: "The neighborhood", field: "category" },
  { label: "The vibe", field: "mood" },
  { label: "Where-ish", field: "setting" },
  { label: "Two ingredients", field: "ingredients" },
] as const;
